### ISSUE TITLE
Current build broken (`spatial.datasources')

### ISSUE THREAD

**Issue by justinmillar** [mdsumner/whatarelief#14]
Hello!

After upgrading to 4.3.2, I am now struggling to get this package re-installed. I tried installing directly from https://hypertidy.r-universe.dev/, but it looks like both `whatarelief` and `spatial.datasources` are failing their build checks. 

Is it possible to patch, or has the package been sunset? I hope not, it's been a frictionless method for getting elevation data!

Thanks!

**Comment by mdsumner** [comment]
I will fix, glad to know it's of use!

btw spatial.datasources was renamed to sds, so you might need to update scripts at your end

(I use it often and it was too much typing)

**Comment by mdsumner** [comment]
ah sorry, yes that was exactly the problem at my end!  I haven't used this package in a while, thanks for the note!

**Comment by justinmillar** [comment]
Awesome, thanks for the quick patch and the package! It's been great for pulling elevation data, which our team often uses in malaria risk models. It makes it much easier to pull systematically, rather than have to track down and manage DEMs. 
I was using it enough that I wrote up a short post on our tech doc blog a little while back: https://path-global-health.github.io/MNTD-tech-docs/posts/elevation-rasters/
